### ISSUE TITLE
Implement "external-name" Annotation

### ISSUE THREAD

**Issue by Kidswiss** [vshn/provider-exoscale#78]
### Summary

**As** VSHNeer
**I want** to be able to adopt existing DBaaS services
**So that** I can adopt manually restored instances

### Context

Crossplane uses an annotation called crossplane.io/external-name to track the name of the actually created resource on the cloud. This annotation can be used to adopt already existing resources into Crossplane.

Our provider-exoscale currently handles the name for the created instance differently. This breaks the adoption functionality. Also it doesn't follow Crossplane's specifications how to implement naming, which could also lead to other issues down the road.

The adoption part already works out of the box with our provider. However, it only works when we use the provider directly eg. when defining a `postgresql.exoscale.crossplane.io` object manually. It will fail when using the composition.

Setting the external name for a new instance also works when using the provider directly.
However, it fails when using the composition. It is able to create the instance, but afterwards can't reference it anymore, because it uses the wrong name to reference the instance.

### Out of Scope

TBD

### Further links

1. Description of the external-name annotation: https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#external-resource-name

### Acceptance Criteria

* Security implications: it could allow adoption for any user. We need a way to restrict it so only cluster admins can do it.
* Implemented Crossplane's suggested logic:
  * If `crossplane.io/external-name` annotation has a value use it.
  * Use managed resource's name and write that into `crossplane.io/external-name` annotation.
  * Use the value of that annotation as external resource name in all queries. 
* Testing: 
  * Manually create a DbaaS instance on Exoscale and try to adopt it with the `crossplane.io/external-name` annotation
* Documentation:
  * Document any pitfalls for the adoption process

### Implementation Ideas

1. see notes

### Notes

* We already have a field to specify the name, we should deprecate it and use the `crossplane.io/external-name`
* We also want to give the ability to specify the `crossplane.io/external-name` in the claim level. So, if `crossplane.io/external-name` is given before the creation of managed resource, we should copy its value to managed resource's `crossplane.io/external-name` annotation before we create it. Note that you never override managed resource's annotation if it already exists. Then in the next reconciles, we always get the value from managed resource and copy it to `crossplane.io/external-name` annotation of Claim.

**Comment by lieneluksika** [comment]
Is already implemented
