### ISSUE TITLE
Plan for supporting compute resource

### ISSUE THREAD

**Issue by matejhasul** [vshn/provider-exoscale#91]
### Summary

Hi there,
any plans support for exoscale compute resource as crossplane crd.

Since exoscale has already developed terraform provider, I'm curious if you were not thinking about using [upjet](https://github.com/upbound/upjet) to convert TF provider into crossplane provider?

Thanks for the info.

### Context

No context, just want to know whether future is bright.

**Comment by tobru** [comment]
> any plans support for exoscale compute resource as crossplane crd.

We're ready to accept contributions to the Crossplane provider to add other Exoscale resources as well.

> Since exoscale has already developed terraform provider, I'm curious if you were not thinking about using [upjet](https://github.com/upbound/upjet) to convert TF provider into crossplane provider?

The first iteration of the provider was based on upjet, but we decided to go the native way, as it's easier to maintain for such a small provider like this one. We were able to be much faster this way.

**Comment by matejhasul** [comment]
@tobru Thanks for the answer.
